### ISSUE TITLE
Non working

### ISSUE THREAD

**Issue by AparnaBhatta14** [ZainMustafaaa/HealthCare-Scan-Nearby-Hospital-Locations#1]
THe source code is not working .
its showing too many errors.
The emulator is not showing any result.
kindly help me out.

**Comment by kiduyu-klaus** [comment]
code updated, check the updated code

**Comment by ZainMustafaaa** [comment]
@kiduyu-klaus  thanks for your commits. @AparnaBhatta14  updated code has been merged.
